### ISSUE TITLE
how to make a restart time

### ISSUE THREAD

**Issue by yoyo00x** [Cr4xy/agar-lvlgen#12]
how to set time of restart

**Comment by hassanila** [comment]
I will make a PR about it
Not now though

**Comment by hassanila97** [comment]
Not now though

**Comment by yoyo00x** [comment]
ok thanks

**Comment by yoyo00x** [comment]
i get a max of 30 bots now :/

**Comment by hassanila** [comment]
Same, and I see bots everywhere that aren't logged in, meaning no skin. nothing... idk  Agar.io is maybe patching them again

**Comment by yoyo00x** [comment]
rip lvl bot ;-;

**Comment by ForgottenEmpire** [comment]
I need the restart thing asap

**Comment by hassanila** [comment]
Restart thing?  What OS?

**Comment by ForgottenEmpire** [comment]
I want every 2 mins the start.bat closes and start again because If I leave it for more than 2 mins it connects 0 bots so autorestarting is the best

**Comment by ForgottenEmpire** [comment]
and what do u recommend 3x mass boost or 3x xp boost? for the bot to level up fast

**Comment by hassanila** [comment]
3x xp boost is the best but if you can both

**Comment by hassanila** [comment]
You can make it restaft every 2 mins but you must know at least the basic JS

**Comment by ForgottenEmpire** [comment]
can u do it for me
pls?

**Comment by ForgottenEmpire** [comment]
I don't know what js even means ( its a programming lang I only know that)

**Comment by hassanila** [comment]
`setTimeout( function() {
process.exit();
}, 2 * 60 * 1000);`

**Comment by ForgottenEmpire** [comment]
where to put that

**Comment by ForgottenEmpire** [comment]
and how to make it start again I  understand that code. it does stop it after 2 \* 6 \* 1000

**Comment by hassanila** [comment]
Best to put it in the beginning of lvlgen.js

**Comment by ForgottenEmpire** [comment]
and which line to put it in
sorry for the noobish me.

**Comment by ForgottenEmpire** [comment]
ah then how to make it start again auto?

**Comment by hassanila** [comment]
I cant guide you by text...  I need to have teamviewer access ...  but Im busy now.. sry

**Comment by ForgottenEmpire** [comment]
just type it :P

**Comment by hassanila** [comment]
Im not even on my pc r now.... so...  just get the Start.bat from the repo and do what I said... put the exit code on the first line before everything else

**Comment by ForgottenEmpire** [comment]
setTimeout( function() { process.exit(); }, 2 \* 60 \* 1000); 
// Made by Cr4xy
// https://www.youtube.com/channel/UC1CJCNc6rrtjJzxiqYN97aQ

var agarClient = require("agario-client")
    config = require("./config.js"),
    token = null,
    account = new agarClient.Account(),
    STATIC_NAME = config.name,
    debugObj = {},
    regions = config.regions;

var VERSION = 0.91;

account.c_user = config.c_user;
account.datr = config.datr;
account.xs = config.xs;

Array.prototype.contains = function(eleme

**Comment by hassanila** [comment]
Yes

**Comment by ForgottenEmpire** [comment]
it will stop after 2 mins right?

**Comment by ForgottenEmpire** [comment]
then it'll start

**Comment by ForgottenEmpire** [comment]
it did work

**Comment by hassanila** [comment]
Ok... good..np

**Comment by ForgottenEmpire** [comment]
Thanks!

**Comment by ForgottenEmpire** [comment]
2 \* 60 \* 1000
2 is what
60 is what
1000 is what
just to understand

**Comment by ForgottenEmpire** [comment]
aw its milliseconds

**Comment by hassanila** [comment]
Almost any programming lang. uses milliseconds... so thats why we use `2 * 60 * 1000`  so it equals 120000 ms  meaning 2 mins

**Comment by caveman1973** [comment]
It exits after 2 min. Where is the code to restart?

**Comment by hassanila** [comment]
If you r on Windows you must start the bots trough the batch file

**Comment by caveman1973** [comment]
Im using Mac (starting with Start.command).

Can I simply put process.restart instead of process.exit?

**Comment by makandz** [comment]
I'm not sure if the mac and Linux loop commands are the same. You can try pulling the command from the .sh file to the .command file see if it works?

@caveman1973 That won't work, once you end a process you can't open it again without something opening it.

**Comment by hassanila** [comment]
@MastaCoder No. .sh and .command are almost completely differnt so it will not work.  Just google how to do a loop in mac command line

**Comment by makandz** [comment]
idk. Some commands from Linux _might_ work on Mac because they're both built on Unix :+1:

**Comment by makandz** [comment]
Fixed in #32
