### ISSUE TITLE
can you creat a mass spawning bot

### ISSUE THREAD

**Issue by yoyo00x** [Cr4xy/agar-lvlgen#13]
like a static bot the destroys the server like 2000 bots all guests ?

**Comment by hassanila** [comment]
never (then how can we play?)

**Comment by ghost** [comment]
Moneyclip will be angry for you, at least if you destroy with your personal IP address. Sending lots of bots to server would be counted as a DOS attack, not sure about it.

And what's your point? If you destroy the game, there will be no game, and using this wil be less fun.

Create your own small Ogar server and destroy it, if you really want to destroy something.
