### ISSUE TITLE
Mac OS X version?

### ISSUE THREAD

**Issue by caveman1973** [Cr4xy/agar-lvlgen#14]
I'm not a programmer.

For what I understand, there is node.js for Mac. Is there a way to make agar-lvlgen work in Macs?

**Comment by hassanila** [comment]
Yes, but currently FB bots are not working...  Agar.io just patched them yesterday -_-

**Comment by makandz** [comment]
@hassanila97 They are working, except you can only spawn one =(

@caveman1973 This works the exact same as it would on Mac. Simply open terminal, cd into the directory and type in `node lvlgen.js`

**Comment by itsBOTmon** [comment]
https://www.youtube.com/watch?v=Iw9qYDU_r8U I have a tutorial on how to do it on mac, hope it helps

**Comment by caveman1973** [comment]
I figure it out.

1 - Install node.js
2 - Run Start.command (open with Terminal)

**Comment by hassanila** [comment]
@Cr4xy Close.
