### ISSUE TITLE
Better Start.bat (Never errors) (full afk)

### ISSUE THREAD

**Issue by J0113** [Cr4xy/agar-lvlgen#15]
Here is my version of start.bat this will fix the problems that people have when the program crashes: if you change the start.bat to this than if the program crashes it will restart automaticly!

```
@echo off
:1
node lvlgen
goto 1
```

Have fun with leveling up without problems!
(btw this isn't a real issue!)

**Comment by hassanila** [comment]
I have a system indipendent restart... (maybe I'll make a PR)

**Comment by makandz** [comment]
Made a PR #19 with this just a bit neater. (Also added one for Linux users too)

**Comment by MuzammilAnsari999** [comment]
Can you please tell us what to do step by step

**Comment by makandz** [comment]
@noob6486 what do you mean?
