### ISSUE TITLE
I Got Banned

### ISSUE THREAD

**Issue by lekrsu** [Cr4xy/agar-lvlgen#16]
I think I got banned on my Facebook account. I can no longer login with my facebook to agario. I tried to make a new facebook, that I didn't use this program on and it worked.

Is it only me this happend to? I'm locked out

**Comment by alexneventchin** [comment]
you cant log in when program is on.

**Comment by lekrsu** [comment]
That's not it. I do not have the program on. And i've tried to log on using a different wifi network. I can play agar.io. But I cannot login with my facebook, but I can use other accounts. It will not allow me to login...

**Comment by dawitrange** [comment]
I just keep refreshing and waiting it works for me when i refresh and wait like 2mn
