### ISSUE TITLE
Agar-Lvlgen error on startup

### ISSUE THREAD

**Issue by tilda** [Cr4xy/agar-lvlgen#18]
**Here;**

C:\AgarLvl\agar-lvlgen-master\lvlgen.js:188
                for (var i in bots) bots[i].client.disconnect();
(sorry for crap formatting) :P                                                      ^

TypeError: Cannot read property 'disconnect' of undefined
    at null._repeat (C:\AgarLvl\agar-lvlgen-master\lvlgen.js:188:37)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

I'd like this fixed soon.
Thank you!
- xsD

**Comment by Cr4xy** [comment]
Should be fixed now. :)

**Comment by tilda** [comment]
Thank you!
