### ISSUE TITLE
I see people getting 400+ bots i do get 80 why?

### ISSUE THREAD

**Issue by ForgottenEmpire** [Cr4xy/agar-lvlgen#20]
my config:
module.exports = {
    // Required
    c_user: "Hidden",
    datr: "Hidden",
    xs: "Hidden",

```
name: "nUll Clan!",

// Advanced
botLimit: 10000,
spawnDelay: 1,
servers: {ffa: true, teams: false, experimental: true, party: true},
regions: ["BR-Brazil", "CN-China", "EU-London", "JP-Tokyo", "RU-Russia", "SG-Singapore", "TK-Turkey", "US-Atlanta"],
statusDelay: 20
```

}

and the level up-ing is too slow

**Comment by hassanila** [comment]
Plz read other issues before opening useless ones

**Comment by ForgottenEmpire** [comment]
what to do just say to me.

**Comment by hassanila** [comment]
Agar.io patched FB bots... meaning you can have max 1 Fb acc. On the whole Agar.io...   so it's now useless but you can have 1 bot only.....   you get 80 because 1 is a real bot logged in and 79 are bots with 10 mass that are not logged in...  so you are just wasting your cpu

**Comment by ForgottenEmpire** [comment]
so I make the max bots 1 and delay 10 is it good?

**Comment by hassanila** [comment]
Yes

**Comment by ForgottenEmpire** [comment]
Yay it became zeros everything :(

**Comment by ForgottenEmpire** [comment]
Nvm, worked
