### ISSUE TITLE
The start.bat dont work

### ISSUE THREAD

**Issue by zakariatelmoudi** [Cr4xy/agar-lvlgen#21]
when i open start.bat i have this 
http://prntscr.com/ahpy7n
i edit config with my fb cookies but its not working
plz help

**Comment by Cr4xy** [comment]
Your cookies are wrong, you should check them. (Maybe you just copied half of a cookie, i recommend http://editthiscookie.com)

**Comment by zakariatelmoudi** [comment]
No I Put mY cookies 
correct

**Comment by ebil-recycle-bin** [comment]
Are you sure you logged into Facebook? If you didn't, the cookies would be different than if you had.

**Comment by zakariatelmoudi** [comment]
I re make my cookies and its work but i dont find the bots in party Help plsss

**Comment by ebil-recycle-bin** [comment]
agar-lvlgen makes the bots on all of the servers; it doesn't put it on just the one server you're playing in. That's part of the reason why when the bots were working, you wouldn't see them all flying toward a player.

**Comment by hassanila** [comment]
@Cr4xy Close.
