### ISSUE TITLE
Thanks , good work

### ISSUE THREAD

**Issue by dhal021** [Cr4xy/agar-lvlgen#24]
**Thanks you brother .**

**Comment by hassanila97** [comment]
You welcome bro...  LOL

**Comment by makandz** [comment]
@Cr4xy close :+1:

**Comment by Cr4xy** [comment]
Thanks to you for using! :)

**Comment by hassanila** [comment]
@MastaCoder I read your site and I'm in your exact position hah I've also worked with and can write HTML, CSS, JS, and PHP... and now I want to start with Java and test other langs. C++ .... :)  :+1:

**Comment by makandz** [comment]
:D @hassanila97
