### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by kemalito** [Cr4xy/agar-lvlgen#25]
Hi,

in advance sorry for my english.

I have proxy list that i can use for agar.(each line 5 clients)
but i dont know how to use them right. 
Is it posible and can you help me to use them.

thanks.

**Comment by caveman1973** [comment]
1 Facebook account limit. It doesn't matter how many proxies you have.

**Comment by ncmp** [comment]
Caveman i have a question. I started using bot since agar has patched facebook account limits and i still managed to lvlup from 30 to 39 so the question is was it much better and efficient earlier before the patch?

**Comment by hassanila** [comment]
@suxosuxo123 Yes, it was 200x more efficent..   I got one account from LVL 5 to 45 in 1 full day..  and  2 days after I was LVL 85,   now after the patch I'm LVL 87  :(   but I have LVL 100 in another acc. :)

**Comment by ncmp** [comment]
@hassanila97 wow thats sad man :( I was 1 day late before the patch would hit.

**Comment by hassanila** [comment]
@suxosuxo123 Thats why Agar.io patched it fast, otherwise every1 would get LVL 100 for free....  Think that you team with a lvl 3 noob and he has kraken skin... just wtf

**Comment by ncmp** [comment]
https://github.com/camilleeyries/AGAR-XPBOT How different is cr4xy's bot different from this?

**Comment by hassanila** [comment]
lvlgen is more efficent..  and has cleaner code...  I have helped making AGAR-XPBOT

**Comment by ncmp** [comment]
Is there no way to return the previous efficiency somehow?

**Comment by hassanila** [comment]
Nope... but you can have multiple fb accs. to gain xp in all of them, slowly

**Comment by ncmp** [comment]
yeah thats sad :D feels bad man

**Comment by Cr4xy** [comment]
@suxosuxo123 @hassanila97 I'll maybe add the feature to farm at multiple accounts at once without having to open multiple consoles and configs. :)

**Comment by hassanila97** [comment]
@Cr4xy I read your site and I'm in your exact position hah I've also worked with HTML, CSS, JS, and PHP... and now I awnt to start with Java :)   :+1:
