### ISSUE TITLE
Smart multiple FB bots

### ISSUE THREAD

**Issue by hassanila** [Cr4xy/agar-lvlgen#26]
Now that Agar has patched the xpbots the only thingh left is 1 fb acc for all servers which gives us max 1 working bot :(....   

---

but what about making the bot mega smart? Then we can let it play 24/7 and in a matter of 2 or 3 weeks we have LVL 100..  and in that way we can farm multi fb bots at once...   this features will make this repo unique to anything seen before. BTW I can help with multi FB

**Comment by ncmp** [comment]
Yea but it will be extremely hard to code mega smart xpbots but we could try...

**Comment by Cr4xy** [comment]
I'm thinking about modifying https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js.
It's a great AI, and plays much more efficient then the lvlgen now.

**Comment by hassanila** [comment]
Yes @Cr4xy I wont be that hard.. at least its in JS

**Comment by ncmp** [comment]
Yea indeed thats a good idea. I think we should give it a go.

**Comment by xxxsomethingxd** [comment]
yeah i would get lvl 100, im stuck at lvl 80 :P good luck

**Comment by clairekardas** [comment]
@Cr4xy @hassanila97 are  you guys already experimenting with agar.io mobile?
i found out that i can use agar lvlgen or an other pc session and play on mobile at the same time with one fb acc.
so maybe we can run the bots over agar mobile?
idk where the mobile servers are saved and how it works but i know http://m.agar.io and http://m.agar.io/fullInfo, what is used for agar lvlgen..
Btw dont know what things like this http://m.agar.io/?_=1430395742677 are but i found it over google with site:agar.io, also wired is http://ip-45-118-135-86.tech.agar.io/proberv.php :D But maybe I/We can look into the agar mobile things with wireshark for android or something, my device is rooted so i can probably test it out.. hope not everything is shit what i said and you understand my bad englisch lol

Edit: that cookies i get from mobile, i found an m_user id but thats all.. the user id c_user is the same like on pc.. i will try to use agar lvlgen with the mobile cookies

```
Cookie: m_pixel_ratio=3.5; wd=732x412; datr=-ejyVkxTa5-HCRX9wCE1Z1nQ; c_user=100007472852077; fr=0AjghQ2J9EVlLiThW.AWXt0FYtIAE3SXfuIBclnbkn6J8.BW8ukP.dB.AAA.0.AWXdF4tR; xs=230%3AApn-yBvAbTMFdA%3A2%3A1458759951%3A11668; csm=2; s=Aa6-AfzHd0XkA5ip.BW8ukP; m_user=0%3A0%3A0%3A0%3Av_1%2Cajax_0%2Cwidth_0%2Cpxr_0%2Cgps_0%3A1458759951%3A2; lu=Rh9FY2zDGD4KygUeTTWoXvfg

data=%5B%7B%22user%22%3A%22100007472852077%22%2C%22page_id%22%3A%22py6ixr%22%2C%22posts%22%3A%5B%5B%22logger%3APlatformOAuthDialogClientEventsLoggerConfig%22%2C%7B%22app_id%22%3A%22677505792353827%22%2C%22event_name%22%3A%22total_time%22%2C%22step%22%3A%22confirm%22%2C%22login_id%22%3A%22a551b61e-827f-4162-8d58-87c979a639c6%22%2C%22time_spent_milli%22%3A737%2C%22start_time%22%3A1458759954205%2C%22end_time%22%3A1458759954942%7D%2C1458759954943%2C0%5D%5D%2C%22trigger%22%3A%22logger%3APlatformOAuthDialogClientEventsLoggerConfig%22%7D%5D&ts=1458759954945&ph=V3&m_sess=&fb_dtsg=AQEKcWPRa8Th%3AAQH4LX8oNEZM&__dyn=1Z3p40x846AeDgy78a8C3q12wAxu0T86u0-E&__req=3&__ajax__=true&__user=100007472852077HTTP/1.1 200 OK
```

Edit 2:
I tried to make agarlvl gen work with the mobile but it says "No mode/region enabled or found. oh well" :\
here is how i used the cookies, (with that from browser and same script it works):

```
module.exports = {
    // Required

    accounts: [
        {
            c_user: "100007472852077",
            datr: "j7PyVjq0M9xgAusOSBnPLcSf",
            xs: "243%3AlnxixjJpYWQcPg%3A2%3A1458746265%3A11668"
        }
    ],

    name: "[KØD] ηυκΦς",

    // Advanced
    regions: ["BR-Brazil", "CN-China", "EU-London", "JP-Tokyo", "RU-Russia", "SG-Singapore", "TK-Turkey", "US-Atlanta"],

    statusDelay: 1,
    botLimit: 200,
    spawnDelay: 1,

    /* Possible values:
     *
     * default: Primitive "AI", low cpu usage
     * apos: Smart AI, higher cpu usage (still buggy)
     * 
    */
    ai: "apos"
}
```

**Comment by makandz** [comment]
Login and out of Facebook real quick so these cookies don't work ^_^

**Comment by clairekardas** [comment]
but is there any method to use agar lvlgen with the "bug" that you can login on mobile multiple times?

**Comment by Cr4xy** [comment]
@christopherkardas Very interesting! I will have a look at it tomorrow. :)

**Comment by makandz** [comment]
@christopherkardas But the issue is mobile is built differently then web. We don't know if it supports ws connections, heck, even if agario-client supports it lol.

**Comment by mastkilxp** [comment]
well in im for the mobile script we we all will work together i am pretty sure we can make a mobile extensions although it will be hard for sure :/ im in if u guys need any help.

**Comment by AbelCz** [comment]
Is lvlgen working with multiple fb again?

**Comment by makandz** [comment]
@AbelCz If you're fine with getting them banned, yep.

**Comment by AbelCz** [comment]
@MastaCoder I am 100% sure, someone can do an unban-script...

**Comment by clairekardas** [comment]
M8.... What is an unban-script lol? An script that edit or delete something on moneyclip servers? Nice try dude :D

**Comment by hassanila** [comment]
@christopherkardas No, he means to make a bot that is undetectable. And yes it is **100%** possible to make it

**Comment by clairekardas** [comment]
An undetectable bot is possible, yeah. But an unban script sounds bit different..
