### ISSUE TITLE
how i can set bot limit

### ISSUE THREAD

**Issue by firo22** [Cr4xy/agar-lvlgen#27]
hey sir , how i can add 100 bot ?

**Comment by caveman1973** [comment]
You can't. Agar was patched. Only 1 possible.

**Comment by firo22** [comment]
is not patched work fine with old version i have 100 bot

**Comment by hassanila** [comment]
@firo22 It's patched 100% and you have 99 fake bots playing without your fb and only 1 is really logged in :P

**Comment by firo22** [comment]
Ahhh ok thx you , you can help me to find bot help fedder ?

**Comment by hassanila** [comment]
@firo22 There is no solution and will never be available to get back the xp bots as they were.  You can have multiple FB accs. farming at same time with smart AI ...  just update and read the README.md

**Comment by firo22** [comment]
ok bro thx youuu :+1:
