### ISSUE TITLE
Only 1 bot

### ISSUE THREAD

**Issue by bonomofelipe** [Cr4xy/agar-lvlgen#29]
Hey, when i add my data, it only connects and spawns 1 bot, how can i change to 200 for example??
I added the command botLimit:100, etc and than I have no bots spawning...

**Comment by hassanila** [comment]
@bonomok It spawns one bot because Agar.io patched FB bots... but you can use multiple FB accs. to have more than 1 bot, but the XP gain will be very slower :P .. (edit config.js like this:)

```
    accounts: [
        {
            c_user: "c_user",
            datr: "datr",
            xs: "xs"
        },
        {
            c_user: "c_user",
            datr: "datr",
            xs: "xs"
        }
    ],
```

**Comment by bonomofelipe** [comment]
Oooh i see, but then each FB account will be leveling up, right?

**Comment by hassanila** [comment]
Yes   slowly

**Comment by bonomofelipe** [comment]
Hmmm, i see, thats too bad, i loved when we were able to use our fb account in more than 1 pc, i leveled up like 40 levels in 1 day hahaha, anyway, thanks a lot, and thanks for the developers!!

**Comment by hassanila** [comment]
Np

**Comment by clairekardas** [comment]
So we can run this 24/7 with 150 fb accs on an raspberry pi and sell the high lvl accs on ebay? :p @hassanila97

**Comment by ebil-recycle-bin** [comment]
From what I've been hearing, they patched it on Facebook but not on Google Plus yet. If we find a way to do it on G+, then we could run multiple bots on one G+ account.

**Comment by hassanila** [comment]
Yes, @ebil-recycle-bin but it will be hard work wasted.... They will patch it very easily,  so that's not the way to go.....      @christopherkardas  Yes, you can make a great business, if people don't find out how-to :P

**Comment by ncmp** [comment]
@ebil-recycle-bin haha nice idea. I think theyve patched google plus too but we dont know about it because we never used g+ to start with. anyway lets suggest some ideas and why not create a skype group?

**Comment by hassanila** [comment]
@suxosuxo123 A skype group is nice but it will be spammed and you can remove users but you cant ban :(

**Comment by makandz** [comment]
@hassanila97 In a p2p Skype group you can xD We just need a server to host it on >.>
