### ISSUE TITLE
Testing out a new Mac OSX script

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#31]
I of course don't own a mac, (because PCMasterRace that's why) and I googled a bit finding the following below, can someone test this on there mac possibly to see if it works? Edit the old command text and change to this:

```
bash -c 'while [ 0 ]; do date;
node $(cd "$(dirname "$0")"; pwd)/lvlgen.js
done'
```

**Comment by makandz** [comment]
DOES NO ONE HAVE A MAC? lol

**Comment by clairekardas** [comment]
Seems the agario community is intelligent enough to dont buy this crap :p
Saw many hero members are on IOS/Mac, but there also not very intelligent lol

**Comment by makandz** [comment]
I honestly think we should drop Mac development and leave it up for themselves to figure it out. That could be just me though :D

**Comment by hassanila** [comment]
I am with you @MastaCoder   Mac and All Apple products are crap XD
