### ISSUE TITLE
Smart Bot: apos

### ISSUE THREAD

**Issue by moerderin** [Cr4xy/agar-lvlgen#33]
@Cr4xy , I just downloaded and started running your bot.  Great documentation. I am using the new apos bot code and it looks pretty good.

Couple of things that look "broken" are the wall-detection code, and then after a while the bot just starts to sit there like it got tired of eating...

These issues may be related, and doing a diff, I saw that you took out lots of apostolic's wall detection code. I was going to look into this and possibly add back the wall detection code that you deleted, but don't want to duplicate efforts since you seem incredibly active compared to the other bot developers.

Thoughts?

**Comment by Cr4xy** [comment]
Hello!
Im currently not working on the apos-AI, so you can modify it how you want.
Thank you!
