### ISSUE TITLE
Not connecting?

### ISSUE THREAD

**Issue by Salvationdk** [Cr4xy/agar-lvlgen#35]
Added all the right data in config but still getting this

```
{ connected: 0,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0,
  time: 17 }

{ connected: 0,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0,
  time: 18 }

{ connected: 0,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0,
  time: 19 }

{ connected: 0,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0,
  time: 20 }
```

**Comment by clairekardas** [comment]
your cookies are not working, try them add again like in the readme or watch an YouTube vid about it, the owner has an channel too :grin:

**Comment by Salvationdk** [comment]
i just added the cookies

**Comment by Salvationdk** [comment]
`[Account 1] Token Success:  EAAJoMBwWJiMBALZCL********Ka1obxmEpm1jhYRpsrIk49kvZBfKYpX9oDUAizubUAjRQZBJe41wLr0j83bopWm*******BSGxIfxlsx7S4HzEp*****wblIhLgYZBZCgLo2C28hn******rrZBMdIhPjzO8Mw4YMTbWjZBS9j***s3h`

**Comment by clairekardas** [comment]
Your config should look like this

```
module.exports = {
    // Required
    accounts: [
        {
            c_user: "100007472852077",
            datr: "j7PyVjq0M9xgAusOSBnPLcSf",
            xs: "243%3AlnxixjJpYWQcPg%3A2%3A1458746265%3A11668"
        }
    ],

```

delete the cookies from facebook and login again in agar and use that new cookies, it should work.

**Comment by Salvationdk** [comment]
it works now... didnt do the above, but repasted my cookie, and then it worked :) strange

**Comment by clairekardas** [comment]
No problem, maybe you forgot an letter or something.. happy farming :wink:

**Comment by makandz** [comment]
@Salvationdk Sometimes when you login and out of Facebook they change. Make sure not to use the account _as much_ while the farmers on :+1:
