### ISSUE TITLE
reset timer

### ISSUE THREAD

**Issue by Salvationdk** [Cr4xy/agar-lvlgen#36]
wrong calculation

`reset: 30, // Minutes before server reset. (0 for none)`

should be
`reset: 30, // seconds before server reset. (0 for none)`

**Comment by clairekardas** [comment]
there is already an request [https://github.com/Cr4xy/agar-lvlgen/pull/34], it will fixed in next update.

**Comment by Salvationdk** [comment]
didnt read that :)
