### ISSUE TITLE
Bot stop working after a few minutes

### ISSUE THREAD

**Issue by xxxsomethingxd** [Cr4xy/agar-lvlgen#37]
i let it work like 40 minutes and after it shows up 0 connected the whole time, maybe you need to set a restarter

**Comment by Salvationdk** [comment]
there is already in config.js

`reset: 1800, // Minutes before server reset. (0 for none) (1800 = 30min)`

**Comment by clairekardas** [comment]
Yeah like @Salvationdk sayed add the line or download the new version. Does other people using your acc or do you login on other devices when you use agar lvlgen?

**Comment by 007Unknown** [comment]
@skillize once you have opened agar-lvlgen-master, you close other agario tabs, if you dont the bot cant start and will say 1:connected ; 0:spawned
