### ISSUE TITLE
G+ Support

### ISSUE THREAD

**Issue by gabe555** [Cr4xy/agar-lvlgen#42]
Looking forward to this implementation bro, this might be the best bot around the whole internet.
Hope you guys can afford it soon. Greetins.

**Comment by makandz** [comment]
#2

**Comment by gabe555** [comment]
There must be more people waiting for this (?

**Comment by makandz** [comment]
Yeah, it's the second issue lol

**Comment by hassanila** [comment]
Yes Im one of those people...   but you must goto Agario-clients issues not here...

**Comment by clairekardas** [comment]
Too bad, maybe moneyclip can transfer the acc to same named face acc when you ask them with much love... And pay them? :p

**Comment by hassanila** [comment]
Hah you think MoneyShit will ever do that? LoL   Btw I scammed them and buyed invisible skin with free 10000 coins... for real  (tools needed: BRAIN)

**Comment by clairekardas** [comment]
Invisible skin is not really good._.
But.. How do you get such much coins?
Bug, carding..?

**Comment by hassanila** [comment]
Refund on Google Play... you can do it for each account I think ... LOLLLL

**Comment by gabe555** [comment]
haha, cool hassalina97, u got hope? or thinkin about to make a new account linked to facebook? xD
I'm level 71 btw, fully obsessed to reach level 90 for raptor skin, its so hard...

**Comment by hassanila** [comment]
I know its hard... for real Im LVL 56   but I got another acc. With LVL100 from a guy here...    Im thinking of making like 20 fb and farm them then likt them with my bots on Ogar-feeder-bots     check it out som1 made a PR with full mouse control... they fully work.. but use them as much as possible before Agar Patch  :)

**Comment by clairekardas** [comment]
Google  dont let me make in app puchases refunds, only when i call them and then only in 1 month interval xD... Do it a LITTLE BIT too often xD Now im do it over an second google acc..

**Comment by hassanila** [comment]
Wtf I get every refund in 1-2 days... sometimes only minutes  Where do you live?

**Comment by clairekardas** [comment]
lol, im too but when i ask for one i often didnt get one.. like i said i do it too often i coc and so on or cheat me apps. I live in austria^^

**Comment by ncmp** [comment]
@hassanila97 add me in skype: sulxani300 please, got few questions. 
@christopherkardas i made once a 5$ refund in coc :p havent tried since then. I bought 5th builder and the next day i had -500 gems on my account XD

**Comment by clairekardas** [comment]
Dear Google Play-User,

we got your refund requst for Coins - Promo (Agar.io). We are sorry but we cant refund your order.

![unbenannt](https://cloud.githubusercontent.com/assets/15703840/14031135/aac509c4-f20b-11e5-9bd3-28cfdd704e85.png)

**Comment by ncmp** [comment]
@christopherkardas how much coins did you buy?

**Comment by clairekardas** [comment]
I refund 30 ordes since 09.April 2014

**Comment by hassanila** [comment]
@suxosuxo123   my Skype:  hassanila97@hotmail.com

**Comment by ncmp** [comment]
@christopherkardas yes but in CoC it is useless because when you refund you get negative number of gems...

**Comment by hassanila** [comment]
@suxosuxo123 Wrong email... updated

**Comment by clairekardas** [comment]
really?
idk I dont play it anymore :D only agar.io^^ @suxosuxo123

**Comment by ncmp** [comment]
hassan i added you

**Comment by clairekardas** [comment]
I add you too, plz answer Hassan ily plzzz lol

**Comment by hassanila** [comment]
@  some ppl think im craz by playin Agar.io...  but its the best game XD

**Comment by ncmp** [comment]
Yeah same here my brother and my frends think im crazy but Im really addicted to getting lvl 100 as soon as possible.

**Comment by clairekardas** [comment]
Lol

**Comment by clairekardas** [comment]
@hassanila97 @suxosuxo123 Called google today for 19,99€ to refund it, now also on this way they will proof it and mail me again in the next days, maybe i get the money back :D For the next puchase i will use an other acc lol

**Comment by 007Unknown** [comment]
@christopherkardas I didnt understand, you guys buy things and want the refound? xD

**Comment by clairekardas** [comment]
Yeah, buy it, use it, get money back.

**Comment by 007Unknown** [comment]
@christopherkardas How the hell can I do it? Lol... Is that some glitch? O.o
#creepy

**Comment by clairekardas** [comment]
No, thats an service from an accommodating company that you can misuse a couple times :)
Lol hope that was englisch what i spoke xD

**Comment by makandz** [comment]
Duplicate reports. #2
