### ISSUE TITLE
Token Fielded ?!

### ISSUE THREAD

**Issue by NoorAgario** [Cr4xy/agar-lvlgen#45]
When i start the bat file it keeps saying Token Failed ? i need help I'm stuck at level 56 :(

**Comment by clairekardas** [comment]
Get new xs and datr and put it into config then restart the bat^^

**Comment by makandz** [comment]
Your tokens are wrong.

**Comment by clairekardas** [comment]
Lol.
What i should do, my token faild?._.
Uhm.. Your token is wrong xD

**Comment by ebil-recycle-bin** [comment]
Download a new copy and do it again. Compare what you copy and paste into the new one and the cookies in your browser and make sure they are the same.

**Comment by hassanila** [comment]
If you ever logout from that FB acc. the coolies will be invalidated

**Comment by NoorAgario** [comment]
got it just close this :/

**Comment by makandz** [comment]
@Cr4xy
