### ISSUE TITLE
No XP gained?

### ISSUE THREAD

**Issue by AlhassanKH** [Cr4xy/agar-lvlgen#47]
Hello, I started the bots for some hours now, later I closed terminal and opened the game to see how much XP I got, It didn't update. 
Help? 
I'm restarting It, but should I open the game while the bot is RUNNING OR CLOSE THEN OPEN?

**Comment by clairekardas** [comment]
Copy and paste new cookies and close your browser then run agar lvlgen and it should work.

**Comment by AlhassanKH** [comment]
Alright, thanks. 
Working now. Takes forever.

**Comment by makandz** [comment]
@Cr4xy Close?
