### ISSUE TITLE
Is node.exe really needed?

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#48]
Yeah this is the question I had. It's almost the biggest file, why would we have use for it xD

**Comment by clairekardas** [comment]
Lol.
Idk, maybe we should remove it from git and tell everyone he MUST use the new version to tell us how it works xD

**Comment by Cr4xy** [comment]
It's there for the users, so they don't need to install node.js. I tested it in a VM and it works.
Should i remove it anyway?

**Comment by clairekardas** [comment]
I wanna see there faces then they havent installed node and it doesnt exist anymore in lvlgen c:

**Comment by hassanila** [comment]
**What r u saying guys...  Node.js is required, 99% of lvlgen is written in JS, so it's required to have Node.js but that file node.exe is the replacement of Node.js so you don't need to install it....   Your choice, that file or Node.js** :+1:

**Comment by makandz** [comment]
People that use this file _should_ probably have Node.js installed on there PC already. Honestly I think lot's of people already have Node.js (Ogar, feeder-bot, etc) and this file is just there for a VERY small majority. I wouldn't have really cared if it didn't take up most of the package space.
