### ISSUE TITLE
Multiple bots at once?

### ISSUE THREAD

**Issue by chinchin160** [Cr4xy/agar-lvlgen#49]
i see that some people are spawning in 10-50 bots in while i only have 1 bot spawning at a time? Please help

```
                         -a coding noob
```

**Comment by clairekardas** [comment]
Yeah, but when 50 bots spawn only 1 bot really get the xp, the others are not connected to facebook. Having more bots only rape your cpu.

**Comment by makandz** [comment]
Moneyclip patched the ability to spawn in with 10-50 bots. People that spawn in with that much are just wasting there resources because 9-49 of the bots aren't spawning with Facebook.

**Comment by chinchin160** [comment]
what is the max number that you can spawn in while still connected to facebook?

**Comment by clairekardas** [comment]
1,0

**Comment by chinchin160** [comment]
is that a ten or 1.0

**Comment by clairekardas** [comment]
Lol, yeah only one.

**Comment by chinchin160** [comment]
can i run start.bat multiple times and have it work?

**Comment by clairekardas** [comment]
nope.

**Comment by chinchin160** [comment]
completely unrelated but there is now an easy to follow tutorial for this! https://youtu.be/5AhVm69QK3c

**Comment by clairekardas** [comment]
Like the other 27 000 on yt? Lol but yeah thats from the new version, watched it and its... Good :)

**Comment by NoorAgario** [comment]
so when ill we get it to be 10 atleast cuz 1 is rly slow , especially when ur lvl 50+ ? is it possible to have more that 1 running ?! @christopherkardas

**Comment by clairekardas** [comment]
You can run 9 million bots, but it doesnt matter, only one will play real and give you xp.

**Comment by NoorAgario** [comment]
can this be ever fixed ?! 
Another Question , if I leave my bot for 24 Hours How much xp should I gain in average !?! 
@christopherkardas

**Comment by clairekardas** [comment]
1. For now not.
2. damn.. Idk.. 150 000?

**Comment by 007Unknown** [comment]
@christopherkardas I had a bot playing 77minutes, with triple xp mass & boost that gave me 18990XP

**Comment by clairekardas** [comment]
Wtf... Lucky boy.
