### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by beaaan** [Cr4xy/agar-lvlgen#5]
Im using ubuntu.I hope u can make a ubuntu version

**Comment by StorminNC** [comment]
go to nodejs.org and download the linux binary for node and run "node lvlgen.js"

**Comment by beaaan** [comment]
bean07@Vostro-3560:~/Desktop/agar-lvlgen-master$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/bean07/Desktop/agar-lvlgen-master/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/bean07/Desktop/agar-lvlgen-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/bean07/Desktop/agar-lvlgen-master/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bean07/Desktop/agar-lvlgen-master/npm-debug.log
npm ERR! not ok code 0
bean07@Vostro-3560:~/Desktop/agar-lvlgen-master$ node Start

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/bean07/Desktop/agar-lvlgen-master/Start'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
bean07@Vostro-3560:~/Desktop/agar-lvlgen-master$ node lvlgen.js

/home/bean07/Desktop/agar-lvlgen-master/lvlgen.js:39
ttps://raw.githubusercontent.com/Cr4xy/agar-lvlgen/master/version', (res) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
bean07@Vostro-3560:~/Desktop/agar-lvlgen-master$ 
help me

**Comment by ghost** [comment]
**No.** Start is .bat file which function is to execute `node lvlgen` - so you need to execute it.

**Comment by makandz** [comment]
Added a .sh script for Linux users #19.

**Comment by hassanila** [comment]
@Cr4xy Close.

**Comment by makandz** [comment]
@Cr4xy Close :3

**Comment by clairekardas** [comment]
On Linux the reset option from the config.js doesnt work, when i put in 600 the bot will end after some minutes, but dont restart. Idk if this is an issue or only doesnt work with my terminal (lx terminal on raspberry pi 2)

**Comment by makandz** [comment]
@christopherkardas In the latest version you can't choose the number of bots though.

**Comment by clairekardas** [comment]
Not the number of bots, ik thats patched and out of the lvlgen bot code.
I mean the reset that the cmd restart.

**Comment by makandz** [comment]
Weird. Can you set the server reset to 1 and then run the bot. Does the time go over 60 when it logs?

**Comment by clairekardas** [comment]
Stops after 1sek and close the bot but terminal is still open and wait for an command, now i can again type in node lvlgen.js, same thing again.

**Comment by makandz** [comment]
Open the terminal, cd into that directory and type in node lvlgen.js, you are probably getting an error :-1:

**Comment by clairekardas** [comment]
Uhm.. Nope?
Why it should?
Bot working for 1 sek and close again. Like everytime with this config.
Im edited it now again to 0, but i want an restart interval like it works on windows, i let it run 24/7 and dont want that it run 12 hours in night but dont farm cause an error :/

**Comment by makandz** [comment]
I actually haven't checked the latest version on my Linux server yet, I'll test it out today.

**Comment by clairekardas** [comment]
Nice :)
Btw wich level are you?

**Comment by hassanila** [comment]
100.. thx to lvlgen

**Comment by clairekardas** [comment]
Lol, k

**Comment by hassanila** [comment]
You?

**Comment by clairekardas** [comment]
Uhm.. 48 😅 but im only play on mobile.. its much harder to get xp here.. Sometimes we play at shool with that acc, im the only one that can connect to the agar servers there with an console script, then we get much xp.. But since the patch with only 1 on 1 fb acc it only work on one pc.. We saw slowly that we cant use skins over connect to servers without xs and datr, then the mass and xp boosts stoped working and.. I think now also to get xp.
Can i share you the script and maybe you have an idea with the tokens and so on? :D

**Comment by hassanila** [comment]
I now how to make fb tokens array and also multiserver... and more but Im so busy.... I also love to play on mobile... its much harder as it is zoomed in as fuck.. but anyway :+1:

**Comment by beaaan** [comment]
Can we using socks to login fb account? if we can do that may be we can do a bot for owner :D

**Comment by makandz** [comment]
@bean07 It won't work if you use sock proxies or not. It's 1 login at a time.
