### ISSUE TITLE
I'm going to close this soon :3

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#50]
Look at my next pull request :+1: It's a bit buggy, but still works!

https://gyazo.com/f2f800be92e1e584066f8045d49c6d10

**Comment by clairekardas** [comment]
Nice! Very clean and beautiful, keep going :)

**Comment by makandz** [comment]
Fixed the long text bug, every 10 seconds it will clean the console.

https://gyazo.com/8513ba6573acd27439460eff9656130b

Adding the pull request now :3

**Comment by Cr4xy** [comment]
Amazing! :)

**Comment by clairekardas** [comment]
Jeej, Cr4xy is here :D cant wait to test it^^

**Comment by makandz** [comment]
@Cr4xy Can I also remove node.exe or is it needed? >.>

**Comment by clairekardas** [comment]
remove it, remove it, remove it! :D what do you think @Cr4xy ? Lol

**Comment by makandz** [comment]
#51!!!
