### ISSUE TITLE
Bug ?!

### ISSUE THREAD

**Issue by NoorAgario** [Cr4xy/agar-lvlgen#52]
How can I know if the bot I working or not ? sometimes it just freeze at 
spawned: 0 | Total: 0 | Average: 0 | Highest: 0 | Time: 174
and sometimes it stuck ok a number like 
spawned: 1| Total: 44 | Average: 44 | Highest: 44 | Time: 120

**Comment by NoorAgario** [comment]
should I leave my browser opened why doing this ?!

**Comment by makandz** [comment]
First one just happens. I think it is when something goes wrong, that's why the reset time is useful for those times. Also for the staying on one amount is because the bot, is staying on one amount. Either it's not eating or running away from something. Use the apos bot for better performance though.

**Comment by 007Unknown** [comment]
@NoorAgario I recomend you set reset to 10(minutes)
@MastaCoder : I dont know java script but, did you already put a code to, if they do not gain mass by some time (+than 10secs) or if mass score is 0 or 0 spawned they reset? That will be helpful I think! :+1:

**Comment by clairekardas** [comment]
Or only reset when when the bot died, sometimes it reset on 400 mass, thats annoying.

**Comment by 007Unknown** [comment]
@christopherkardas yes. it would be like that..

**Comment by makandz** [comment]
I want the bot to split into max the last 10 seconds of reset, so that someone would eat it. I think that method would work the best.

**Comment by makandz** [comment]
@christopherkardas #53

**Comment by clairekardas** [comment]
Thx bæ <3 xD
