### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Oqtions** [Cr4xy/agar-lvlgen#54]
Whenever I go to start it it says this:
module.js:341
    throw err;
    ^

Error: Cannot find module './ai/default_ai.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\derek\Downloads\agar-lvlgen-master\agar-lvlgen-master\lvlgen.js:11:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
 Press any key to continue . . .

**Comment by makandz** [comment]
Do you have the ai folder?

**Comment by Oqtions** [comment]
No I do not, how can I get it?

**Comment by clairekardas** [comment]
From git, download agar lvlgen again.

**Comment by Oqtions** [comment]
The whole .zip file?

**Comment by clairekardas** [comment]
No, the half lol.
Yeah download the full zip and unzip it and copy the cookies from your olf config

**Comment by hassanila** [comment]
No... aproxemately 25% of the zip is needed....  LOLOLOLOLOLoL

**Comment by Oqtions** [comment]
I got it to work, but now it says this and the bots will not spawn.
{ connected: 0,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0 }
{ connected: 8,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0 }
{ connected: 5,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0 }
{ connected: 7,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0 }
{ connected: 6,
  spawned: 0,
  totalScore: 0,
  avgScore: 0,
  highest: 0 }

**Comment by makandz** [comment]
Make sure not to be logged in at the time it's running. Also double check your tokens.

**Comment by 007Unknown** [comment]
@Oqtions that an old version. Use the latest version

**Comment by Oqtions** [comment]
Should I log out of Facebook on agario?  MastaCoder?

**Comment by clairekardas** [comment]
No, then the token is invaild.

**Comment by Oqtions** [comment]
How do I get the latest version?  Whenever I download the .zip this is what it gives?

**Comment by clairekardas** [comment]
Download the zip and you have the latest version, easy ha? Lol

**Comment by Oqtions** [comment]
It doesnt give the latest version, it gives the version I currently have which is 0.9.

**Comment by Cr4xy** [comment]
Did you download https://github.com/Cr4xy/agar-lvlgen/archive/master.zip?

**Comment by Oqtions** [comment]
I will redownload it now and see what it says.

**Comment by Oqtions** [comment]
Okay, it is working now.  This is what it says, tell me if this is what its supposed to say?

########################
    _                         _         _  ____
   / \   __ _  __ _ _ __     | | __   _| |/ ___| ___ _ __
  / _ \ / _`|/ _` | '__|____| | \ \ / / | |  _ / _ \ '_ \
 / ___ \ (_| | (_| | | |_____| |**\ V /| | |_| |  __/ | | |
/_/   \_\**, |__,_|_|       |______/ |_|____|_**|_| |_|
        |_**/ - Open Source Agar.io Level Farming!

Running version: 0.95 (Latest)
Will reset in: 0 minutes

########################

Spawned: 0 | Total: 0 | Average: 0 | Highest: 0 | Time: 1

## Live Console:

[ac1] Token Success: Token Hidden!
Spawned: 1 | Total: 62 | Average: 62 | Highest: 62 | Time: 93

**Comment by clairekardas** [comment]
Yeah works fine.

**Comment by Oqtions** [comment]
Is it supposed to spawn more than 1?  Because this is what mine says.
Spawned: 1 | Total: 44 | Average: 44 | Highest: 44 | Time: 881

**Comment by clairekardas** [comment]
Moneyclip patched it... Yes only one bot...

**Comment by Oqtions** [comment]
Okay cool, thank you guys for the help.

**Comment by clairekardas** [comment]
Glad to help :)

**Comment by makandz** [comment]
@Cr4xy Close or @Oqtions Close :+1:
