### ISSUE TITLE
[bug] Apos bot: version 0.95

### ISSUE THREAD

**Issue by 007Unknown** [Cr4xy/agar-lvlgen#55]
Sometimes the bot doesnt spawn... And doesnt reset.. What should I do?
<a href='http://postimg.org/image/xy3dx7pxp/' target='_blank'><img src='http://s14.postimg.org/xy3dx7pxp/image.jpg' border='0' alt="ew" /></a>

**Comment by clairekardas** [comment]
New tokens

**Comment by 007Unknown** [comment]
@christopherkardas  So.. should I wait?

**Comment by clairekardas** [comment]
No, get new cookies, dont login into face or agar and set the reset timer to 10 or 30, when your using the newest version its recommend to use 10, works much better :)

**Comment by makandz** [comment]
@HugoMSantos Don't log out of Facebook :+1:

**Comment by 007Unknown** [comment]
@christopherkardas & @MastaCoder Thank you.
