### ISSUE TITLE
Like a BOSS ! Linux Elementary OS + Virtualbox with Agar-LVLGEN on Windows 7 !!!

### ISSUE THREAD

**Issue by W1LKC0** [Cr4xy/agar-lvlgen#56]
![capture du 2016-03-28 01 08 39](https://cloud.githubusercontent.com/assets/18109984/14071385/22397b48-f482-11e5-9749-0975f9f7dc99.png)

Done.

![capture du 2016-03-28 11 37 53](https://cloud.githubusercontent.com/assets/18109984/14081614/92587792-f4d9-11e5-8bf7-dd523d37db7e.png)

**Comment by Cr4xy** [comment]
Very nice, I like the background. :P

**Comment by W1LKC0** [comment]
Thank you very much :)

**Comment by makandz** [comment]
Why did you make a Windows VM to run this? Can't you just run it on Linux? lol

**Comment by W1LKC0** [comment]
I know lol but just for fun ;)

**Comment by makandz** [comment]
Ahaha nice :+1:

**Comment by W1LKC0** [comment]
Its done ;) linux too :P

**Comment by W1LKC0** [comment]
For background:
http://www.elementaryos-fr.org/wallpapers/

@Cr4xy @MastaCoder 

Elementary OS is based unfortunatly on Ubuntu...but... its a beautiful OS like MAC OS.

My lunchpad profile, im official translator for Elementary OS

https://launchpad.net/~ismael-cormier

**Comment by makandz** [comment]
I would run Linux, just all my favorite programs alternatives suck. It's just too hard to use, I HAD TO OPEN THE TERMINAL TO CHANGE MY SCROLL WHEEL SPEED. **THE GOD DAMN TERMINAL!**

**Comment by W1LKC0** [comment]
@Cr4xy: I take this opportunity to express to you my gratitude for your really great software.
