### ISSUE TITLE
Using proxy is not an good idea...

### ISSUE THREAD

**Issue by W1LKC0** [Cr4xy/agar-lvlgen#59]
Because search for this f***king proxy list will take more time at each day of my life... :(

**Comment by makandz** [comment]
lol nobody is adding it yet.

**Comment by clairekardas** [comment]
uhm.. i can gave you an proxy list with 500 000 ips in 5 minutes^^ :joy:

**Comment by makandz** [comment]
But they have to be working, we don't want something spending 6 minutes finding a working proxy and crash :)

**Comment by clairekardas** [comment]
yeah, there is a good german site that provide thousands of free working proxys updated every minute :)

**Comment by 007Unknown** [comment]
@christopherkardas working every time? I dont think so, haha :p

**Comment by clairekardas** [comment]
Yeah, 99%

**Comment by NoorAgario** [comment]
What do u even need from Proxies ?! can I run multiple bots ?!

**Comment by W1LKC0** [comment]
@NoorAgario running multiple bots are not an good idea... because agar-lvlgen connect into facebook account for play and facebook autorize only one account for play.

**Comment by 007Unknown** [comment]
@W1LKC0 He's saying like other accounts.. and even better: the G+ ACCOUNT! So you can up twice... or more accounts! That will be better :3 :+1:
