### ISSUE TITLE
Interested in Collaboration?

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#67]
@Cr4xy I see you're quite busy and we might have different timezones :) (I like in Canada)

If it's possible you can make me a collaborator or somewhat so I can help keep everything stable while you're gone? (And so I can push updates without the stupid PR xD)

You don't have to :+1:

**Comment by Cr4xy** [comment]
Yes, indeed.
Have fun pushing :)

**Comment by makandz** [comment]
:tada: Thanks! :tada:
