### ISSUE TITLE
Multiple smart bots

### ISSUE THREAD

**Issue by 007Unknown** [Cr4xy/agar-lvlgen#70]
How do I add multiple bots?
I cant just repeat like this

```
accounts: [
    {
        c_user: "c_user1",
        datr: "datr1",
        xs: "xs1"

        c_user: "c_user2",
        datr: "datr2",
        xs: "xs2"
    }
],
```

What should I do? #noob ? xD

**Comment by Cr4xy** [comment]
Read the README.md at the front page, it shows how to have multiple accounts. :)

**Comment by 007Unknown** [comment]
@Cr4xy thank you.
