### ISSUE TITLE
G+ Bug ?!

### ISSUE THREAD

**Issue by NoorAgario** [Cr4xy/agar-lvlgen#71]
Did MoneyClip Patched The Gmail Bug ? can we play with more than 1 acc and get xp ?!

**Comment by clairekardas** [comment]
Uhm..?
Google+, Gmail, more than one acc.. I dont get it xD
Do you mean the only one bot problem and g+ support?._.

**Comment by NoorAgario** [comment]
Yep

**Comment by clairekardas** [comment]
Same as before^^

**Comment by NoorAgario** [comment]
so is it patched or not ?!

**Comment by clairekardas** [comment]
We never used g+ in agarlvlgen

**Comment by NoorAgario** [comment]
yes but if  I opened more than 1 tab and I get them all in 1 acc 
will it give me all the xp ?!

**Comment by clairekardas** [comment]
2 cmds with same fb acc?

**Comment by NoorAgario** [comment]
Nope I mean if I opened a lot of tabs and I singed all of them in the same Gmail Account (without using agar level gen) will I get all the xp from all the tabs or only from 1 ?!

**Comment by clairekardas** [comment]
Try it out, when youre using the same browser and handle it to play in 4 sessions at the same time it can maybe work.. But yeah try it out.

**Comment by NoorAgario** [comment]
hey @christopherkardas  I have a question for ya . can we run that agar-lvl gen on c9.io so it wont eat my own internet :/ I cloned the files but I don't know how to run that bat file

**Comment by clairekardas** [comment]
Lol, im running it since 2PM on c9.io... Already tryed it out but it stoped sometimes... And you must run the sh file or type node lvlgen.js in terminal :)
