### ISSUE TITLE
Running lvl-gen on C9.io Or Koding ?!

### ISSUE THREAD

**Issue by NoorAgario** [Cr4xy/agar-lvlgen#72]
Hey , is it possible to run the lvl gen at c9.io or koding so it wont eat my bandwidth ?! and if yes then how cuz I cloned the file and I don't know what todo now . like how can I run that start.bat ?!

**Comment by clairekardas** [comment]
Lol, im running it since 2PM on c9.io... Already tryed it out but it stoped sometimes... And you must run the sh file or type node lvlgen.js in terminal :)
Can it be that c9.io stop working after an amount of time?._.

**Comment by hassanila** [comment]
Yes c9.io has 2hrs limit on free version then you must restart.   Its fully possible to run it on c9 just use .sh or terminal instead of .bat

**Comment by ItzLevvie** [comment]
@hassanila97 before they used to have a 1 week limit, but they changed it to 2 hours now.

**Comment by NoorAgario** [comment]
thnx

**Comment by NoorAgario** [comment]
guys I got an error Error: Cannot find module '/home/ubuntu/workspace/node_modules/lvlgen.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by clairekardas** [comment]
So we cant run it there over night? :/
Fuck.. :D
Kk, is there any other method to run it and dont use the own cpu power and our electricity? :3 btw how much it can cost per day to run an I7 with 16GB ram and so on without monitor? ._.

**Comment by NoorAgario** [comment]
@christopherkardas  what should I do with that error ?!

**Comment by NoorAgario** [comment]
nvm I figured it out

**Comment by clairekardas** [comment]
Kk :)

**Comment by hassanila** [comment]
@christopher other method... yes...   a vps.   You can get one for free but you need valid cc

**Comment by clairekardas** [comment]
Yeah.. Vps.
But you know i dont have an cc lol^^
Does they check them really or does fake or old stolen ccs work when i use the free offer?
Wich vps i sould use?

**Comment by hassanila** [comment]
They check for validity... almost every1 does nowadays....  old stolen card will most prob. not work...  I use Amazon ec2 free tier..  if you want it to be 3x fast, use the nearest region to you

**Comment by clairekardas** [comment]
Tryed it out, cant get Microsoft azure or amazon ec2 to work.. An agar bot skype group told me they trade free vps, but im left.. Is this real?
And again does someone know how much it cost to run an pc 24/7?

**Comment by hassanila** [comment]
Most free vps that r not from famous companies are bullshit and they scam...   I wouldnt recommend you to use them....     A pc running 24/7 would consume almost nothing if have only lvlgen running.   You can test your energy cost with some tools/programs I think...

**Comment by clairekardas** [comment]
Kk, my pc is runnig now and i use it over team viewer cause im in my 2. home now lol^^
Thx hassan :)

**Comment by makandz** [comment]
Guys buy a cheap 258MB Ram VPS off the internet, they are like $10 / Year. :+1:

**Comment by hassanila** [comment]
258mb ram isnt that much.. lol

**Comment by makandz** [comment]
I have mine running on a 1GB Ram VPS with 1 vCPU and around 120MB of the ram is in use with Agar-Lvlgen open, while 8% of the CPU used at _max_.

Remember 120MB of the ram is used for both the OS and the bot.

**Comment by hassanila** [comment]
Nice then
