### ISSUE TITLE
Triple Xp and Triple Mass Boost problem

### ISSUE THREAD

**Issue by heyghost** [Cr4xy/agar-lvlgen#73]
in the middle of the night, my computer updated to windows 10. i have the current version of the software and now my triple xp and triple mass boost isn't working with the program anymore...any thoughts on this?

in fact, upon further testing, i am not even gaining any xp anymore. cookies are copied correctly form facebook. please help. thanks.

**Comment by NoorAgario** [comment]
same :( it stopped like 2 hours ago it's not spawning with 50 mass or giving me any xp :(

**Comment by moerderin** [comment]
If it makes you feel any better, I got banned overnight...

**Comment by NoorAgario** [comment]
wutt
will using this may get u banned ?!! @moerderin

**Comment by NoorAgario** [comment]
should I stop using it ? I don't wanna risk my acc cuz its lvl 56 and it took me like a year

**Comment by makandz** [comment]
You guys are right. I just double checked and I can confirm the Facebook login isn't working anymore. Seems like an agario-client issue?

@pulviscriptor You know what's going on? @Cr4xy Can you confirm this too?

**Comment by makandz** [comment]
Nevermind. Found a commit at agario-client that looks like it has fixed this. I am testing it now.

https://github.com/pulviscriptor/agario-client/commit/a9023a792650927b1d4d6eaf9adf4aab568899e3

**Comment by makandz** [comment]
Update again: That commit doesn't do it. I guess we just have to wait for @pulviscriptor and see what's wrong with the packets to login and if something got updated..

**Comment by NoorAgario** [comment]
:( I just made a video on yt 4 hours ago and now it stopped working :/ that gonna be a lot of dislikes

**Comment by Cr4xy** [comment]
@MastaCoder @NoorAgario Can confirm. Agar also now has a updated server version, 1.3.22.
It seems that the authentication now is in the miniclip-protocol, I think opcode 82 has been removed.

**Comment by Cr4xy** [comment]
Made an fix, please tell if it works for you. :+1:

**Comment by clairekardas** [comment]
Also notice it and saw in an agar group that fb bots are patched, but an half hour later they updated the files and it worked again lol^^

**Comment by NoorAgario** [comment]
hey @Cr4xy  @christopherkardas  mine just stuck at 
Spawned: 1 | Total: 44 | Average: 44 | Highest: 44 | Time: 614
and keeps like that for ever

**Comment by clairekardas** [comment]
Updated to 0.97?

**Comment by NoorAgario** [comment]
yep

**Comment by clairekardas** [comment]
New cookies?

**Comment by megadaboss** [comment]
It is happening to me too... And could you work on a coin hack????? 
@Cr4xy @christopherkardas

**Comment by clairekardas** [comment]
"Coin hack"? Lol.
No, but maybe an auto coin grabber, every hour 20 coins^^

**Comment by hassanila** [comment]
Yeah thats what hes calling coin hack :P...

**Comment by clairekardas** [comment]
But maybe @megadaboss can hack into Moneyclips servers and edit the values for us :p

**Comment by makandz** [comment]
@Cr4xy I just woke up, had a crazy essay to do last night :) I'll check if it works when I come back from school, or if I can in the next 5 minutes :+1:

**Comment by clairekardas** [comment]
Lol, checked the time in canada, you get ready for school, mine is over since an hour :D @MastaCoder

**Comment by makandz** [comment]
Alright I just installed it and confirm it works :+1: Good work @Cr4xy!
