### ISSUE TITLE
Multiple acc not working

### ISSUE THREAD

**Issue by yoyo00x** [Cr4xy/agar-lvlgen#74]
i tried doing 2 accs on the same time but all what i got is only 1 acc working.... any fix?

**Comment by 007Unknown** [comment]
@yoyo00x 
Idk dude, just one works, two or more doesnt... Just the first cookies work :c

```
accounts: [
     {
            c_user: "c_user",
            datr: "datr",   //this one works
            xs: "xs"
     },
        {
            c_user: "c_user",
            datr: "datr",   //this doesnt
            xs: "xs"
 ],
```

**Comment by clairekardas** [comment]
That should work :)

accounts: [
        {
            c_user: "c_user",
            datr: "datr",
            xs: "xs"
        },
        {
            c_user: "c_user2",
            datr: "datr2",
            xs: "xs2"
        }
    ],
