### ISSUE TITLE
Just sayin'

### ISSUE THREAD

**Issue by jerzabek** [Cr4xy/agar-lvlgen#75]
I just got banned for using agar levelgen. Nothing against the creator or the program, its awesome, but you should know that they can ban you for using it. Just sayin'.

Not ban as in ban, but they reset ur account to level 1 and take your skins

**Comment by clairekardas** [comment]
Do you edit the bots name or was it agar-lvlgen?

**Comment by jerzabek** [comment]
I called my bots doge.

**Comment by clairekardas** [comment]
Wich version you use?

**Comment by jerzabek** [comment]
I was banned while 0.96 was running.

**Comment by clairekardas** [comment]
Mine acc is bugging, at pc i dont see my xp when i login and it dont show my name  and so on, maybe an other pc or browser is logged in at the moment and i dont know it.. Also agar lvlgen stopped working for me :c
On mobile i can use agar same as before, can u test if it work there?

**Comment by jerzabek** [comment]
I talked to a dev on reddit (Zeach) and he told me that im banned, honestly idk about mobile since i dont use it but you could be banned

**Comment by clairekardas** [comment]
Lol, sounds sweet moneyclip.

**Comment by jerzabek** [comment]
Ik, but still I kinda aprove it since thats how they get rid of bots. :/

**Comment by Cr4xy** [comment]
I saw it, https://www.reddit.com/r/Agario/comments/4cl4vq/i_keep_getting_instantly_kicked/.
I think it's time to stop.. :(

**Comment by clairekardas** [comment]
But we only use 1 fuckn bot. One.
Like when we play normal.

**Comment by clairekardas** [comment]
Jep, i think im banned.

**Comment by Cr4xy** [comment]
I will make an update telling the people to don't use it anymore, but it seems it's already too late...
Sorry @christopherkardas, @JarzaGM and anyone else who got banned.

**Comment by 007Unknown** [comment]
@Cr4xy I got banned to. I already spend 50$ into the game.

**Comment by 007Unknown** [comment]
@Cr4xy 
Okay. theres not more an level 72 account with a tound of skins :/

**Comment by clairekardas** [comment]
No problem m8, i can play on mobile... may I stop fully playing agar, moneyclip may notice that and do something.. #stopbots to #stopagar lol

**Comment by 007Unknown** [comment]
@christopherkardas 
On reddit there's a guy who says that we can't login into the web because he used to a feeder(faster w) and he got banned to. Can they know that we use agar-lvlgen or other program?

**Comment by 007Unknown** [comment]
#moneyclip :: Trading bans because bots for a small loan. thats good for them, more space :+1:

**Comment by clairekardas** [comment]
Yeah, they can notice it. I spoke to Hassan on skype :/
He is working on an new version but WE are banned now :c

**Comment by 007Unknown** [comment]
@christopherkardas Because I didn't know it, I sent a mail to support.. they will say that I used hack.. -_-

**Comment by 007Unknown** [comment]
Okay.. At least I have an 25lvl account (G+) and a new one that doesnt get banned lvl11(facebook) leveling up with lvlgen.. omg

**Comment by 007Unknown** [comment]
@christopherkardas I noticed too. while I was waiting at the dentist I used my phone and collect the hourly coins... so there's a glitch

**Comment by 007Unknown** [comment]
@Cr4xy So we might be ban if we use BOTS to get an higher score too? O_o

**Comment by clairekardas** [comment]
Mobile dont work like the pc version, also bots should run there.

**Comment by 007Unknown** [comment]
@christopherkardas If they ban because some players use bots.. they will be angry with the companys.. without any reason. :-1: agario in 2015 was :100: % better! :+1:

**Comment by 007Unknown** [comment]
While beta version it was good.. now is a shit that make you lag and you cant use extension or bots or you will get banned... Dooh!

**Comment by clairekardas** [comment]
Yeah.. Fuck moneyclip.. They should never buy agar.io. now its like pay to win.

**Comment by Cr4xy** [comment]
> So we might be ban if we use BOTS to get an higher score too? O_o

If you mean feeder bots, definitively.

**Comment by NoorAgario** [comment]
OMG I GOT BANNED TOO , years of playing on that acc :((

**Comment by NoorAgario** [comment]
cant any 1 hack into agario server and give us some xp or unban /!?

**Comment by 007Unknown** [comment]
@Cr4xy 
Okay... Agar Bots companys like: bagar.io ; raga.pw ; agarbot.ovh ; agarbots.net & more (if idk) will be down too :+1: 
Agario is doing a real patch for that.. Unfortunatelly they will ban the users who used some extension.. like agarplus.io ; agario infinity ; Creative bots.... thats sad for all reasons.

@christopherkardas Yeah agario Is a pay game.. that you need to pay much as you can to level up more.. Since they created the possibility about to have an account.. that ruin the game.. 
To get the newest seasons skins (all of them) You will need like 15k for buy them.. 
#RIP_AGARIO

**Comment by NoorAgario** [comment]
i hate mini-clip

**Comment by 007Unknown** [comment]
@NoorAgario 
Impossible, I think so! I'm just waiting for miniclips answer for the support about that...

**Comment by NoorAgario** [comment]
u kno what this means all youtubers accounts will get banned too , cuz everybody use Agario plus

**Comment by 007Unknown** [comment]
@NoorAgario 
Yes, you're probably right. I used agarioplus.io ; raga.pw ; agarbot.ovh ; agarbots.net ; agar-feeder-bot ; agario inifinity (with skin rotator)....
So that will decrease the amount of players probably to - 40% to -60% , When you join a server you always will see a guy using bots...

**Comment by clairekardas** [comment]
Yeah, agar.io is dead now.
They dont now how many people using bots or something.. when they ban them all..... Moneyclip should die with there fuckn skins and boosts^^ :smiling_imp:

**Comment by Cr4xy** [comment]
Guys, before this turns into a complete hate "issue", i will close this. **Sorry once again for everyone who  got banned.**
