### ISSUE TITLE
banned?

### ISSUE THREAD

**Issue by heyghost** [Cr4xy/agar-lvlgen#76]
can u give us a quick explanation on the new version/why there is a ban risk right now and if it will be safe any time in the near future?

**Comment by clairekardas** [comment]
#75, you can ask there also when its closed lol

**Comment by heyghost** [comment]
ah, thanks

**Comment by NoorAgario** [comment]
i Got banned but ill they get all my coins ?! i had 2k or more

**Comment by 007Unknown** [comment]
@NoorAgario 
No you can't, moneyclip probably will reset your account....

**Comment by clairekardas** [comment]
I had 80 000 and all the good skins lol

**Comment by 007Unknown** [comment]
@christopherkardas what level u r?

**Comment by clairekardas** [comment]
Lvl 59^^

**Comment by 007Unknown** [comment]
@christopherkardas  In other acc?
Man this is bullshit.. 40mass bots, 132 and 10mass bots are better to get XP and us trying to get a little bit higher and they kick us... But who use bots doesnt get banned... thats a desrespect -_-

**Comment by clairekardas** [comment]
In 3 days we can maybe play again^^

**Comment by clairekardas** [comment]
I spoke to the agar io team on the YouTube livestream, our skins and coins and level will be removed.

**Comment by 007Unknown** [comment]
@christopherkardas Ik :/

**Comment by 007Unknown** [comment]
He says that they're banning WHO USES BOTS, BUT THEY'RE BANNING ONLY LVLGEN.

**Comment by clairekardas** [comment]
Lol i spamed the chat with "we will fix agar lvlgen". " bots will never die"... "When you remove our coins we will cheat us new one" Everytime when he read my comments he stucked with speaking :D

**Comment by clairekardas** [comment]
Also gg for the server crasher^^

**Comment by 007Unknown** [comment]
@christopherkardas Yeah. He said the "live <3" evil guy would be banned. I dont think so. #Moneylagclip_bullshits

**Comment by clairekardas** [comment]
Can we report them at the police or something cause they remove our coins?
Did anyone read the Terms? :D

**Comment by 007Unknown** [comment]
@christopherkardas No I Didnt. Sure, go ahead xD

**Comment by clairekardas** [comment]
Naah :D

**Comment by makandz** [comment]
You can't report them for anything. It's in game currency, whenever you spend money, you're basically spending it on nothing. They still own your coins and your account, so they can remove it or do anything they want to it when they want to.

**Comment by hassanila** [comment]
That's why you should buy as much coins as possible and refund them all :)

**Comment by 007Unknown** [comment]
@hassanila97 Yh but, how? I mean.. I can do that because I bought a 50$ package into GooglePlayStore to Moneyclip... What should I do? help pls

**Comment by clairekardas** [comment]
Play.google.com, my account, you see your orders, click on the coins, say something like i dont want them anymore and you get back your money. But missuse this service is illegal, so..... Dont do it... xDD

Sry for the englisch, i use it only in german so i dont know 100% how google named it :)
