### ISSUE TITLE
Bot won't be dead!

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#77]
We have all heard the news about the bot being banned and people using it will be banned. Who in what world thought that a bot will always be, a bot..?

It's pretty-ish easy to fix this. The apos bot is quite close to playing as a real player, and with a mix of not using the bot for 24 hours and having longer reset wait times, it might just work.

But this is where the issue comes in. If Moneyclip does jump in and have some sort of way to check, we are all screwed. If this update ever get's released, DO NOT use it on your main account. There will always be a chance of getting banned!

Of course this will be much less efficient, but we have no choice anymore.

**Comment by Cr4xy** [comment]
It may just be the instant respawn which is not possible in vanilla.

**Comment by makandz** [comment]
@Cr4xy You might be right. But the issue is that we don't know if they have some sort of checker to check if the inbound connection is coming from agario-client. I don't know how they do it, but if that's the case we might have some issues.

I'll do some testing later this week with timed pauses and without instant spawn to check if it works. People have been saying that the fast w ejecting tools screw it up too. I wonder if they are checking if it's ANY mod. If it is, AgarPlus is next to be screwed :(
