### ISSUE TITLE
Connecting (Stats)

### ISSUE THREAD

**Issue by W1LKC0** [Cr4xy/agar-lvlgen#78]
I cannot connect... status are connecting.... and no more... ??? Do you have same shit ???

I think im banned.

**Comment by W1LKC0** [comment]
![capture du 2016-03-30 19 08 50](https://cloud.githubusercontent.com/assets/18109984/14160540/de9aa9fe-f6aa-11e5-8490-c3edf2d2be35.png)

**Comment by rafeeek** [comment]
hhhhhhhhhhhhh banded hhhhhhhhhhhhh

**Comment by makandz** [comment]
Banned.

**Comment by W1LKC0** [comment]
shit.... :(

**Comment by clairekardas** [comment]
May only for 3 days, we have to wait
