### ISSUE TITLE
I can't play on my FB account

### ISSUE THREAD

**Issue by ItzMaxxie** [Cr4xy/agar-lvlgen#81]
For some reason i can not connect to my facebook account and i can't play with it. It keeps changing servers.

**Comment by clairekardas** [comment]
You are banned, pls read the readme.md and the other issues. #80 #79 #78 #76 #77 #75

**Comment by ItzMaxxie** [comment]
So i can never play on this account ever again?

**Comment by clairekardas** [comment]
We dont know, but maybe only for 3 days^^ im too banned, but you can play on mobile with your fb acc.

**Comment by ItzMaxxie** [comment]
I realy hope i don't have it permanent

**Comment by clairekardas** [comment]
Wait some days and you will see it, but please stop now using agar lvlgen and play maybe normal on mobile, delete agar browser extentions if there are any and.. Yeah^^

**Comment by ItzMaxxie** [comment]
Okay. Thanks 4 helping me out :+1:

**Comment by 007Unknown** [comment]
@christopherkardas You can't any more do it on mobile. With the login into banned accs on mobile they cover that.. moneyclip :-1:

**Comment by 007Unknown** [comment]
Moneyclip doesnt answer my question about the ban.. Unfortunately they only ban the lvl-gen users, thats unfair...

**Comment by ItzMaxxie** [comment]
Yeah, its realy unfair

**Comment by clairekardas** [comment]
I can play on mobile lol

**Comment by 007Unknown** [comment]
@christopherkardas I cant. See Agario Livestream : https://www.youtube.com/watch?v=sEwcdpUVo4U
I do a question about bots.. he says that "you will get ban if you use them" BUT THATS ONLY FOR AGAR-LVLGEN.. -_-
