### ISSUE TITLE
I cant believe I just realized this but... 

### ISSUE THREAD

**Issue by ghost** [Cr4xy/agar-lvlgen#82]
You should make a comment in the config saying that you should change the name of the bots so people are less likely to get banned. We don't know how miniclip sniffs out the bots. Most of the Agar.io level farmers use the default name. So that's a big duh to miniclip.

**Comment by clairekardas** [comment]
Please use the other issues, we all know, u get banned for using agar lvl gen, please stop telling us.

**Comment by jerzabek** [comment]
Check #75 bro.
