### ISSUE TITLE
remove apos bot

### ISSUE THREAD

**Issue by jacobduba** [Cr4xy/agar-lvlgen#83]
So today I tried to use the apos tampermonkey bot - it won't let me in unless I disablet.

 It might let other types of bots in, like the default bot in lvl-gen that are not apos. (or even a modded apos bot) Chances are agar.io bans people who try to get into agar.io with apos a certain amount of times.

I looked in the web console and agar.io is closing the socket uses to connect players to it's servers... looks like a simple fix for agar.io.

(srry if you already know this, I thought I'd input what I know)

**Comment by makandz** [comment]
I don't see what the difference between the apos bot and default bot are. Other than it is much smarter. You were never able to log into Facebook with apos-bot using tampermonkey for a while now because it overrides some things that Miniclip found and blocked from signing in.

There are many ideas of how this ban occurs, but the one that makes sense is that Miniclip is seeing us running agar.io clients for 24 hours straight non stop with auto restart.

**Comment by jacobduba** [comment]
mastcoder, agar.io is blocking people using apos bot (apos loader) in the tampermoney script which leads to me to think that this is because of apos bot, not the lvl gen server.

**Comment by makandz** [comment]
We aren't using the apos launcher.

**Comment by WJKH** [comment]
@MastaCoder it's not about running the bot 24 hours, I got new account banned in less than 2-3 hours.

**Comment by clairekardas** [comment]
Maybe cause the user agent?

**Comment by makandz** [comment]
Yeah, it's because they have some sort of detection system.
1. Bot is always stable at around 100 - 1000 mass
2. We keep respawning everytime the bot dies INSTANTLY.
3. Is playing on one server for a whole 3 - 4 hours.
4. User agent could be a possibility. :)

**Comment by clairekardas** [comment]
1. Normal users often too
2. maybe include an 2 sek. Timeout for respawn.
3. maybe we dont have an life lol?
4. yeah.

**Comment by makandz** [comment]
But if you are doing that CONSTANTLY throughout days and days, pretty sure they have people checking stats now.

**Comment by jacobduba** [comment]
yea  but we are using the apos bot.

**Comment by WJKH** [comment]
@MastaCoder
1. No
2. Random time will prevent it
3. I don't believe it's an issue to flag us, maybe if you say 24 hours playing.
4. Yeah!

**Comment by makandz** [comment]
> We aren't using the apos launcher.

The apos bot and apos launcher are completely different things.

**Comment by jacobduba** [comment]
ok
