### ISSUE TITLE
MoneyClip Apologies

### ISSUE THREAD

**Issue by 007Unknown** [Cr4xy/agar-lvlgen#84]
MoneyLagClip Apologies about agar-lvlgen 

In the support I related this issue:
"When I log in into my facebook account, I cant play. There's always a buton saying "connecting". What should I do?"

MoneyLagClip answer is...
![sem titulo](https://cloud.githubusercontent.com/assets/18051575/14204021/48b1670c-f7f9-11e5-9c2e-05a7874a19d1.png)

**Comment by clairekardas** [comment]
Does it work now?
For me and some others it works already after 3 or 2 days :)

**Comment by makandz** [comment]
It works for me now on my test account that got banned. I can play again ;)

**Comment by 007Unknown** [comment]
@MastaCoder Yes!!!
"they should be looking for a solution as we speak" So, they they warned us or it was a glitch. #85

**Comment by HugoMSantos** [comment]
#85

**Comment by jerzabek** [comment]
I just hope its not a glitch XD, or even if it is that they dont fix it haha
because this probbably means the accounts have un-flaged. Yay
