### ISSUE TITLE
Account's unbanned.

### ISSUE THREAD

**Issue by makandz** [Cr4xy/agar-lvlgen#85]
If many of you were online since this morning, you might have realized your account is working fine and nothing has been reset. I feel like since so many people were bugging them about the warning thing on Reddit, they finally decided to do it. 

**I can't tell if this is some glitch or Moneyclip (Miniclip) is actually trying to be nice.** But it looks like they gave everyone a warning. 

Now with a warning comes knowing that if you do use a bot again, you will 99% probably get banned. So just keep an eye out for the next update :+1:

**Comment by 007Unknown** [comment]
@MastaCoder YEEEEEEEEES!! :+1:

**Comment by jerzabek** [comment]
Oh. My. God. YASSS! IM SO HAPPY :D ALL HAIL MONEYCLIP!!

**Comment by W1LKC0** [comment]
Yes my brother have been unban... me too ... and my brother this night have use bot... and he now banned again... its a warning of miniclip... please don't use bot again... you will ban again.

**Comment by makandz** [comment]
> and my brother this night have use bot.

lol

**Comment by dsadassafsafwa** [comment]
Oh fuck i used it ... How to get unbanned ? :C

**Comment by clairekardas** [comment]
Wait max 3 days and you will get unflagged/banned

**Comment by dsadassafsafwa** [comment]
ok thanks

**Comment by Shair17** [comment]
hello good, my account is banned agar.io, logea not only in the cel, help please, :D

**Comment by makandz** [comment]
You can't do anything if you're banned.

> Wait max 3 days and you will get unflagged/banned

**Comment by Drflash55** [comment]
So, you'll just have to find a way to get past the banning system, so you can gain levels in secret...

**Comment by makandz** [comment]
I've been playing around with it for a couple days now and got already 4 accounts banned :| This is going to be harder than it looks :+1:

**Comment by philw1508** [comment]
Whats About Google+ accounts? Is Moneyclip banning them too?

**Comment by clairekardas** [comment]
G+ is not supported, so no.

**Comment by dsadassafsafwa** [comment]
Im now banned 4 days :(

**Comment by hassanila** [comment]
Then youre permanently banned.

**Comment by clairekardas** [comment]
Do you use it again after the ban?

**Comment by dsadassafsafwa** [comment]
No

**Comment by dsadassafsafwa** [comment]
I AM UNBANNED FINALLY :)

**Comment by clairekardas** [comment]
:thumbsup:

**Comment by makandz** [comment]
Quick update to leave here. I was testing a bit more on the bot to see how far I can get to fixing it. I ran the bot for less than 3 minutes and got an IP ban. Looks like they are banning pretty much all agario-client connections.

RIP AgarLvlGen.

**Comment by Drflash55** [comment]
Damn...
