### ISSUE TITLE
developer @Cr4xy @MasterCoder

### ISSUE THREAD

**Issue by agarioBotDev** [Cr4xy/agar-lvlgen#86]
Hello,

I'm currently searching for a partner for my site d-bots.com . It's too much work for one person. Both of you look like skilled developers, not copy-paste ones...if you are interested: email: agarbotsDavid@gmail.com.

I want to make slither.io bots too ! Hope to hear from you !
greats,
david

**Comment by makandz** [comment]
lol. Add me on Skype @youagar and we could talk. :+1:

**Comment by ghost** [comment]
Cr4xy did this all work, Masta just helped him little bit and now he's making money :p

**Comment by clairekardas** [comment]
Like with the facbook founders ;)

**Comment by agarioBotDev** [comment]
@Cr4xy are you interested ?

**Comment by Cr4xy** [comment]
Yes, add @cr4xycode. :)
