### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by NovaHowl** [Cr4xy/agar-lvlgen#90]
I wanted to test this out so I created a fresh facebook account and tried it (Idc if I got banned) and it warned me about getting banned and it doesn't work. Any help?

**Comment by clairekardas** [comment]
You need an older version to get it work, but you will get banned.

**Comment by NovaHowl** [comment]
Do you have any copies of the old version?

**Comment by clairekardas** [comment]
Yeah. But im at school now, you can add me on skype and i can send it maybe :) (Christopher Kardas)

**Comment by makandz** [comment]
Just download from one of the older commits. But to warn you, there is a 99% chance of getting banned.

https://github.com/Cr4xy/agar-lvlgen/tree/c7f1b81c804f487655ebb680c291055059363e8c
