### ISSUE TITLE
Please DO NOT use agar-lvlgen at the moment due the risk of getting banned

### ISSUE THREAD

**Issue by J053Fabi0** [Cr4xy/agar-lvlgen#91]
Please DO NOT use agar-lvlgen at the moment due the risk of getting banned

**HOW CAN I FIX THIS?** 
im using mac

**Comment by clairekardas** [comment]
Uhm.. Thx. But we all know that :)
You cant fix it.

**Comment by J053Fabi0** [comment]
`print ("Do you know an other way to earn xp in agar.io")`

**Comment by clairekardas** [comment]
Yeah. Play agar.io
